const ICON_NAMES = [
  "account_balance",
  "add",
  "add_shopping_cart",
  "architecture",
  "arrow_back",
  "arrow_forward",
  "calculate",
  "check",
  "check_circle",
  "chevron_left",
  "chevron_right",
  "close",
  "delete",
  "draw",
  "edit",
  "expand_less",
  "expand_more",
  "grid_view",
  "handyman",
  "home",
  "inventory_2",
  "logout",
  "mail",
  "publish",
  "remove",
  "schedule",
  "search",
  "share",
  "shopping_bag",
  "unpublished",
  "visibility",
] as const;

export const MATERIAL_SYMBOLS_HREF = `https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0..1,0&display=block&icon_names=${ICON_NAMES.join(",")}`;
